Fix test rest controller
NikitaNesterenko/JM-SYSTEM-MESSAGE pull request #204
Opened 2020-01-14 18:12 UTC by Alexei84-08

Поправил тесты на ChannelRestControllerTest и MessageRestControllerTest

2020-01-15 16:03 UTC, NikitaNesterenko requested changes
убрать пом из коммита

2020-01-15 16:03 UTC, NikitaNesterenko commented on webapp/pom.xml
> -
убрать

2020-01-16 02:20 UTC, Alexei84-08 commented on webapp/pom.xml
> -
Устранил замечание. Файл пом исключен из коммита.

2020-01-24 17:26 UTC, NikitaNesterenko commented on webapp/src/main/java/jm/controller/rest/ChannelRestController.java
> +        return ResponseEntity.badRequest().build();
лишний ретерн + поправить логи

2020-01-27 16:10 UTC, NikitaNesterenko approved these changes

2020-01-27 16:10 UTC, merged