01 04 20 get createDate without other fields
NikitaNesterenko/JM-SYSTEM-MESSAGE pull request #303
Opened 2020-04-01 06:33 UTC by gitpetr

2020-04-02 05:15 UTC, gitpetr commented on webapp/src/main/java/jm/controller/rest/MessageRestController.java
> +import jm.dto.UserDTO;
почему-то этот импорт отсутствует

2020-04-02 05:35 UTC, gitpetr commented
сделал бранч из предыдущего, были же небольшие исправления, не смог работать на неисправленном, оставил комментарии почему были эти исправления сделаны

2020-04-02 08:51 UTC, pkhilenko commented on webapp/src/main/java/jm/controller/rest/ChannelRestController.java
> +            channel.setIsApp(false);
может принимать значения true и false, а получалось null
задать значение по умолчанию в модели не получилось, выдает ошибку, поэтому устанавливаю здесь

2020-04-02 08:51 UTC, pkhilenko commented on webapp/src/main/resources/static/js/workspace-page/components/modal-searcher/workspace-modal-searcher.js
> +window.addEventListener('DOMContentLoaded', function () {
пока все скрипты не загрузились, слушатель не подключается, снята ошибка при создании канала

2020-04-06 16:12 UTC, NikitaNesterenko requested changes

2020-04-06 16:12 UTC, NikitaNesterenko commented on dao-impl/src/main/java/jm/dao/MessageDAOImpl.java
> +            return null;
опшинал вместо нулл

2020-04-06 16:12 UTC, NikitaNesterenko commented on dao-impl/src/main/java/jm/dao/MessageDAOImpl.java
> +                .createQuery("select m.dateCreate from Message m where m.id = :id", Message.class)
переделать на sql, доставать только нужное поле из таблицы

2020-04-13 09:53 UTC, NikitaNesterenko approved these changes

2020-04-13 09:54 UTC, merged