rest controller для workspace
NikitaNesterenko/JM-SYSTEM-MESSAGE pull request #7
Opened 2019-10-06 17:19 UTC by Qustal

2019-10-07 10:58 UTC, NikitaNesterenko requested changes
Написать всё через sql
Убрать тернарники 
Связь Юзера и воркспейса? ( поправь связь если можешь, у юзера может быть много воркспейсов)

2019-10-10 11:22 UTC, NikitaNesterenko requested changes
public void createWorkspace(Workspace workspace) {
- странная логика метода
убрать коммит с пропертями и иницилизатором
OneToMany у сета?

2019-10-12 18:26 UTC, VasiliKnyazev approved these changes
С таблицами вроде всё нормально. Создаются. Только у меня с TestDataInitializer не создались тестовые каналы, пришлось закомментить чтобы запустить.

2019-10-14 22:05 UTC, NikitaNesterenko requested changes
изменить название в соответствии с код стайлом ( без нижних подчеркиваний )
привести дао к актуальному виду
убрать из коммита апдейт мавен зависимости и проперти
+ конфликты

2019-10-16 16:58 UTC, NikitaNesterenko approved these changes

2019-11-16 11:30 UTC, merged